using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FairWorkly.Domain.Auth.Entities;
using FairWorkly.Domain.Common;
using FairWorkly.Domain.Common.Enums;
using FairWorkly.Domain.Employees.Entities;

namespace FairWorkly.Domain.Compliance.Entities;

/// <summary>
/// RosterIssue entity
/// Represents a compliance issue found during roster validation
/// Generated by Compliance Agent's checks
/// Similar to PayrollIssue but for roster/shift compliance
/// </summary>
public class RosterIssue : BaseEntity
{

  /// <summary>
  /// Which organization this issue belongs to
  /// </summary>
  [Required]
  public Guid OrganizationId { get; set; }

  /// <summary>
  /// Navigation property to organization
  /// </summary>
  public virtual Organization Organization { get; set; } = null!;

  /// <summary>
  /// Which validation run found this issue
  /// </summary>
  [Required]
  public Guid RosterValidationId { get; set; }

  /// <summary>
  /// Navigation property to validation
  /// </summary>
  public virtual RosterValidation RosterValidation { get; set; } = null!;

  /// <summary>
  /// Which roster this issue belongs to
  /// </summary>
  [Required]
  public Guid RosterId { get; set; }

  /// <summary>
  /// Navigation property to roster
  /// </summary>
  public virtual Roster Roster { get; set; } = null!;

  /// <summary>
  /// Which shift has the issue (if issue is shift-specific)
  /// Null for employee-level issues (e.g. consecutive days)
  /// </summary>
  public Guid? ShiftId { get; set; }

  /// <summary>
  /// Navigation property to shift
  /// </summary>
  public virtual Shift? Shift { get; set; }

  /// <summary>
  /// Which employee is affected by this issue
  /// </summary>
  [Required]
  public Guid EmployeeId { get; set; }

  /// <summary>
  /// Navigation property to employee
  /// </summary>
  public virtual Employee Employee { get; set; } = null!;

  // Issue Details 

  /// <summary>
  /// Which compliance check found this issue
  /// </summary>
  /// <example>
  /// "Minimum Shift Hours", "Maximum Consecutive Days", "Meal Break", 
  /// "Rest Period Between Shifts", "Weekly Hours Limit"
  /// </example>
  [Required]
  [MaxLength(100)]
  public string CheckType { get; set; } = string.Empty;

  /// <summary>
  /// Severity level
  /// Critical = Must fix before publishing roster
  /// Error = Should fix, Fair Work violation
  /// Warning = Should review, may be acceptable
  /// Info = For awareness only
  /// </summary>
  [Required]
  public IssueSeverity Severity { get; set; }

  /// <summary>
  /// Short description of the issue
  /// </summary>
  /// <example>
  /// "Shift only 2.5 hours, minimum is 3 hours"
  /// "Alice Chen worked 7 consecutive days, maximum is 6"
  /// "No meal break provided for 8-hour shift"
  /// </example>
  [Required]
  [MaxLength(500)]
  public string Description { get; set; } = string.Empty;

  /// <summary>
  /// Detailed explanation (AI-generated by Claude)
  /// </summary>
  /// <example>
  /// "Under the Hospitality Industry Award 2020, the minimum shift duration is 3 hours. 
  ///  This shift is only 2.5 hours (9:00 AM - 11:30 AM), which violates the minimum 
  ///  shift requirement. Employees cannot be rostered for shifts shorter than 3 hours 
  ///  unless specific exemptions apply."
  /// </example>
  public string? DetailedExplanation { get; set; }

  /// <summary>
  /// Recommended action (AI-generated)
  /// </summary>
  /// <example>
  /// "Extend the shift to at least 3 hours (e.g. 9:00 AM - 12:00 PM), or combine 
  ///  this shift with another task to meet the minimum duration requirement."
  /// </example>
  public string? Recommendation { get; set; }

  // Values

  /// <summary>
  /// Expected value (what it should be)
  /// Example: 3 (minimum shift hours)
  /// </summary>
  public decimal? ExpectedValue { get; set; }

  /// <summary>
  /// Actual value (what it currently is)
  /// Example: 2.5 (actual shift hours)
  /// </summary>
  public decimal? ActualValue { get; set; }

  /// <summary>
  /// Difference amount (computed)
  /// Negative = under requirement, Positive = over requirement
  /// Example: -0.5 (0.5 hours short)
  /// </summary>
  [NotMapped]
  public decimal? Variance =>
      ExpectedValue.HasValue && ActualValue.HasValue
          ? ActualValue.Value - ExpectedValue.Value
          : null;

  // Affected Shifts/Dates

  /// <summary>
  /// For multi-shift issues (e.g. consecutive days, rest period)
  /// Comma-separated shift dates
  /// Example: "2025-01-20,2025-01-21,2025-01-22,2025-01-23,2025-01-24,2025-01-25,2025-01-26"
  /// </summary>
  [MaxLength(500)]
  public string? AffectedDates { get; set; }

  /// <summary>
  /// Number of shifts affected by this issue
  /// Example: 7 (for consecutive days issue)
  /// </summary>
  public int? AffectedShiftsCount { get; set; }

  // Resolution

  /// <summary>
  /// Has this issue been resolved?
  /// True = Manager fixed the roster
  /// False = Still needs attention
  /// </summary>
  public bool IsResolved { get; set; } = false;

  /// <summary>
  /// Who resolved it (typically a Manager)
  /// </summary>
  public Guid? ResolvedByUserId { get; set; }

  /// <summary>
  /// Navigation property to resolver
  /// </summary>
  public virtual User? ResolvedByUser { get; set; }

  /// <summary>
  /// When it was resolved
  /// </summary>
  public DateTimeOffset? ResolvedAt { get; set; }

  /// <summary>
  /// How it was resolved
  /// </summary>
  /// <example>
  /// "Extended shift to 3 hours"
  /// "Removed Sunday shift to give employee rest day"
  /// "Added 30-minute meal break"
  /// </example>
  [MaxLength(1000)]
  public string? ResolutionNotes { get; set; }

  //  Waiver/Exception

  /// <summary>
  /// Is this issue waived/accepted by Manager?
  /// Some issues may be acceptable with employee agreement
  /// Example: Employee agrees to shorter shift due to personal circumstances
  /// </summary>
  public bool IsWaived { get; set; } = false;

  /// <summary>
  /// Who waived the issue
  /// </summary>
  public Guid? WaivedByUserId { get; set; }

  /// <summary>
  /// Navigation property to waiver
  /// </summary>
  public virtual User? WaivedByUser { get; set; }

  /// <summary>
  /// When it was waived
  /// </summary>
  public DateTimeOffset? WaivedAt { get; set; }

  /// <summary>
  /// Reason for waiving
  /// </summary>
  /// <example>
  /// "Employee requested shorter shift due to university class"
  /// "Split shift arrangement agreed with employee"
  /// </example>
  [MaxLength(1000)]
  public string? WaiverReason { get; set; }
}