events {
    worker_connections 1024;
}

http {
    client_max_body_size 50m;

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    # UAT
    server {
        listen 443 ssl;
        server_name uatec2.fairworkly.com;

        ssl_certificate     /etc/letsencrypt/live/fairworkly.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/fairworkly.com/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;

        location / {
            proxy_pass         http://backend:5680;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_read_timeout    120s;
            proxy_connect_timeout 10s;
            proxy_send_timeout    120s;
        }
    }

    # Prod
    server {
        listen 443 ssl;
        server_name fairworkly.com www.fairworkly.com;

        ssl_certificate     /etc/letsencrypt/live/fairworkly.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/fairworkly.com/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;

        location / {
            proxy_pass         http://backend-prod:5681;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_read_timeout    120s;
            proxy_connect_timeout 10s;
            proxy_send_timeout    120s;
        }
    }
}
