using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FairWorkly.Domain.Auth.Entities;
using FairWorkly.Domain.Common;
using FairWorkly.Domain.Common.Enums;
using FairWorkly.Domain.Employees.Entities;

namespace FairWorkly.Domain.Payroll.Entities;

/// <summary>
/// Represents a compliance issue found during payroll validation
/// Generated by Payroll Agent's 5 checks
/// </summary>
public class PayrollIssue : BaseEntity
{
    [Required]
    public Guid OrganizationId { get; set; }
    public virtual Organization Organization { get; set; } = null!;

    [Required]
    public Guid PayrollValidationId { get; set; }
    public virtual PayrollValidation PayrollValidation { get; set; } = null!;

    [Required]
    public Guid PayslipId { get; set; }
    public virtual Payslip Payslip { get; set; } = null!;

    [Required]
    public Guid EmployeeId { get; set; }
    public virtual Employee Employee { get; set; } = null!;

    //  Issue Details

    /// <summary>
    /// Which check found this issue
    /// </summary>
    /// <example>
    /// "Base Rate Check", "Penalty Rate Check", "Casual Loading Check",
    /// "Superannuation Check", "STP Compliance Check"
    /// </example>
    [Required]
    [MaxLength(100)]
    public string CheckType { get; set; } = string.Empty;

    /// <summary>
    /// Severity level
    /// </summary>
    [Required]
    public IssueSeverity Severity { get; set; }

    /// <summary>
    /// Short description of the issue
    /// </summary>
    /// <example>"Saturday penalty rate incorrect"</example>
    [Required]
    [MaxLength(500)]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Detailed explanation (AI-generated by Claude)
    /// </summary>
    /// <example>
    /// "Under the Hospitality Industry Award 2020, Saturday work should be paid
    ///  at 125% of the base rate. The employee's base rate is $25.41/hour, so
    ///  Saturday rate should be $31.76/hour. However, the payslip shows $25.41/hour."
    /// </example>
    public string? DetailedExplanation { get; set; }

    /// <summary>
    /// Recommended action (AI-generated)
    /// </summary>
    /// <example>
    /// "Correct the Saturday rate in Xero to $31.76/hour and reprocess payroll.
    ///  The employee is owed an additional $50.80 for this pay period."
    /// </example>
    public string? Recommendation { get; set; }

    // Values

    /// <summary>
    /// Expected value (what it should be)
    /// </summary>
    public decimal? ExpectedValue { get; set; }

    /// <summary>
    /// Actual value (what it currently is)
    /// </summary>
    public decimal? ActualValue { get; set; }

    /// <summary>
    /// Difference amount
    /// </summary>
    [NotMapped]
    public decimal? Variance =>
        ExpectedValue.HasValue && ActualValue.HasValue
            ? ActualValue.Value - ExpectedValue.Value
            : null;

    //  New fields for dynamic description generation
    /// <summary>
    /// Number of units affected by this issue
    /// Examples:
    /// - For rate issues: number of hours worked at wrong rate (8 hours)
    /// - For hours issues: number of hours over limit (15 hours overtime)
    /// - For days issues: number of consecutive days (8 days)
    /// Used to calculate financial impact
    /// </summary>
    public decimal? AffectedUnits { get; set; }

    /// <summary>
    /// Type of unit for values and AffectedUnits
    /// Examples: "$/hr", "hours", "days", "%", "$"
    /// Used for formatting values in UI
    /// Example usage:
    /// - ExpectedValue=31.76, UnitType="$/hr" → display as "$31.76/hr"
    /// - ExpectedValue=40, UnitType="hours" → display as "40 hours"
    /// - ExpectedValue=25, UnitType="%" → display as "25%"
    /// </summary>
    [MaxLength(20)]
    public string? UnitType { get; set; }

    /// <summary>
    /// Context label describing what is being checked
    /// Examples: "Saturday rate", "Ordinary hours", "Casual loading", "Rest period"
    /// Used to build descriptive sentences
    /// Template: "{ContextLabel} {ActualValue}{UnitType} should be {ExpectedValue}{UnitType}"
    /// Result: "Saturday rate $23.50/hr should be $31.76/hr"
    /// </summary>
    [MaxLength(100)]
    public string? ContextLabel { get; set; }

    //  Resolution

    /// <summary>
    /// Has this issue been resolved?
    /// </summary>
    public bool IsResolved { get; set; } = false;

    /// <summary>
    /// Who resolved it
    /// </summary>
    public Guid? ResolvedByUserId { get; set; }
    public virtual User? ResolvedByUser { get; set; }

    /// <summary>
    /// When it was resolved
    /// </summary>
    public DateTimeOffset? ResolvedAt { get; set; }

    /// <summary>
    /// How it was resolved
    /// </summary>
    [MaxLength(1000)]
    public string? ResolutionNotes { get; set; }
}
