using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FairWorkly.Domain.Auth.Entities;
using FairWorkly.Domain.Common;
using FairWorkly.Domain.Common.Enums;
using FairWorkly.Domain.Employees.Entities;

namespace FairWorkly.Domain.Payroll.Entities;

/// <summary>
/// Represents a compliance issue found during payroll validation
/// </summary>
public class PayrollIssue : BaseEntity
{
    [Required]
    public Guid OrganizationId { get; set; }
    public virtual Organization Organization { get; set; } = null!;

    [Required]
    public Guid PayrollValidationId { get; set; }
    public virtual PayrollValidation PayrollValidation { get; set; } = null!;

    [Required]
    public Guid PayslipId { get; set; }
    public virtual Payslip Payslip { get; set; } = null!;

    [Required]
    public Guid EmployeeId { get; set; }
    public virtual Employee Employee { get; set; } = null!;

    // ═══════════════════════════════════════════════════════════════
    //  Issue Classification
    // ═══════════════════════════════════════════════════════════════

    /// <summary>
    /// Category of this issue
    /// </summary>
    [Required]
    public IssueCategory CategoryType { get; set; }

    /// <summary>
    /// Severity level
    /// </summary>
    [Required]
    public IssueSeverity Severity { get; set; }

    // ═══════════════════════════════════════════════════════════════
    //  Issue Content
    // ═══════════════════════════════════════════════════════════════

    /// <summary>
    /// Warning message for data validation issues (Severity = Warning)
    /// Null for underpayment issues (Severity = Error or Critical)
    /// </summary>
    /// <example>
    /// "Unable to verify: Classification is missing or invalid"
    /// </example>
    [MaxLength(500)]
    public string? WarningMessage { get; set; }

    /// <summary>
    /// Detailed explanation (AI-generated by Claude)
    /// </summary>
    /// <example>
    /// "Under the Hospitality Industry Award 2020, Saturday work should be paid
    ///  at 125% of the base rate. The employee's base rate is $25.41/hour, so
    ///  Saturday rate should be $31.76/hour. However, the payslip shows $25.41/hour."
    /// </example>
    public string? DetailedExplanation { get; set; }

    /// <summary>
    /// Recommended action (AI-generated)
    /// </summary>
    /// <example>
    /// "Correct the Saturday rate in Xero to $31.76/hour and reprocess payroll.
    ///  The employee is owed an additional $50.80 for this pay period."
    /// </example>
    public string? Recommendation { get; set; }

    // ═══════════════════════════════════════════════════════════════
    //  Underpayment Evidence
    // ═══════════════════════════════════════════════════════════════

    /// <summary>
    /// Expected value per legal requirement
    /// </summary>
    /// <example>25.41 (hourly rate) or 300.00 (super amount)</example>
    public decimal? ExpectedValue { get; set; }

    /// <summary>
    /// Actual value paid
    /// </summary>
    /// <example>23.50 (hourly rate) or 250.00 (super amount)</example>
    public decimal? ActualValue { get; set; }

    /// <summary>
    /// Difference per unit (ExpectedValue - ActualValue)
    /// </summary>
    [NotMapped]
    public decimal? Shortfall =>
        ExpectedValue.HasValue && ActualValue.HasValue
            ? ExpectedValue.Value - ActualValue.Value
            : null;

    /// <summary>
    /// Number of units affected by this issue
    /// </summary>
    /// <example>
    /// 40.0 (hours at wrong rate) or 2500.00 (gross pay base for super)
    /// </example>
    public decimal? AffectedUnits { get; set; }

    /// <summary>
    /// Type of unit for values
    /// </summary>
    /// <example>"Hour" (hourly rate issues) or "Currency" (amount issues)</example>
    [MaxLength(20)]
    public string? UnitType { get; set; }

    /// <summary>
    /// Context label for display
    /// </summary>
    /// <example>"Retail Award Level 2", "Saturday shift", "12%"</example>
    [MaxLength(100)]
    public string? ContextLabel { get; set; }

    /// <summary>
    /// Calculated underpayment amount
    /// </summary>
    /// <example>
    /// Hourly: (ExpectedValue - ActualValue) × AffectedUnits = 76.40
    /// Super: ExpectedValue - ActualValue = 50.00
    /// </example>
    public decimal? ImpactAmount { get; set; }

    // ═══════════════════════════════════════════════════════════════
    //  Resolution Tracking
    // ═══════════════════════════════════════════════════════════════

    /// <summary>
    /// Has this issue been resolved?
    /// </summary>
    public bool IsResolved { get; set; } = false;

    /// <summary>
    /// Who resolved it
    /// </summary>
    public Guid? ResolvedByUserId { get; set; }
    public virtual User? ResolvedByUser { get; set; }

    /// <summary>
    /// When it was resolved
    /// </summary>
    public DateTimeOffset? ResolvedAt { get; set; }

    /// <summary>
    /// How it was resolved
    /// </summary>
    [MaxLength(1000)]
    public string? ResolutionNotes { get; set; }
}
