import {
  FAIRBOT_FILE,
  FAIRBOT_LABELS,
  FAIRBOT_QUICK_ACTIONS,
  FAIRBOT_QUICK_ACTIONS_TEXT,
} from '../../constants/fairbot.constants'
import type { FairBotQuickAction } from '../../types/fairbot.types'

// Central definition for quick actions shown in the FairBot chat UI.
export const quickActions: FairBotQuickAction[] = [
  {
    id: FAIRBOT_QUICK_ACTIONS.IDS.CHECK_PAYROLL,
    title: FAIRBOT_QUICK_ACTIONS_TEXT.CHECK_PAYROLL.TITLE,
    description: FAIRBOT_QUICK_ACTIONS_TEXT.CHECK_PAYROLL.DESCRIPTION,
    icon: FAIRBOT_QUICK_ACTIONS.ICONS.PAYROLL,
    color: FAIRBOT_QUICK_ACTIONS.COLORS.BLUE,
    requiresFile: true,
    acceptedFileTypes: [...FAIRBOT_FILE.ACCEPTED_TYPES],
    initialMessage: FAIRBOT_QUICK_ACTIONS_TEXT.CHECK_PAYROLL.INITIAL_MESSAGE,
    requiredPermission: FAIRBOT_QUICK_ACTIONS.PERMISSIONS.CHECK_PAYROLL,
  },
  {
    id: FAIRBOT_QUICK_ACTIONS.IDS.CHECK_ROSTER,
    title: FAIRBOT_QUICK_ACTIONS_TEXT.CHECK_ROSTER.TITLE,
    description: FAIRBOT_QUICK_ACTIONS_TEXT.CHECK_ROSTER.DESCRIPTION,
    icon: FAIRBOT_QUICK_ACTIONS.ICONS.ROSTER,
    color: FAIRBOT_QUICK_ACTIONS.COLORS.GREEN,
    requiresFile: true,
    acceptedFileTypes: [...FAIRBOT_FILE.ACCEPTED_TYPES],
    initialMessage: FAIRBOT_QUICK_ACTIONS_TEXT.CHECK_ROSTER.INITIAL_MESSAGE,
    requiredPermission: FAIRBOT_QUICK_ACTIONS.PERMISSIONS.CHECK_ROSTER,
  },
  {
    id: FAIRBOT_QUICK_ACTIONS.IDS.ASK_QUESTION,
    title: FAIRBOT_QUICK_ACTIONS_TEXT.ASK_QUESTION.TITLE,
    description: FAIRBOT_QUICK_ACTIONS_TEXT.ASK_QUESTION.DESCRIPTION,
    icon: FAIRBOT_QUICK_ACTIONS.ICONS.QUESTION,
    color: FAIRBOT_QUICK_ACTIONS.COLORS.PURPLE,
    requiresFile: false,
    initialMessage: FAIRBOT_QUICK_ACTIONS_TEXT.ASK_QUESTION.INITIAL_MESSAGE,
    requiredPermission: null,
  },
  {
    id: FAIRBOT_QUICK_ACTIONS.IDS.GENERATE_CONTRACT,
    title: FAIRBOT_QUICK_ACTIONS_TEXT.GENERATE_CONTRACT.TITLE,
    description: FAIRBOT_QUICK_ACTIONS_TEXT.GENERATE_CONTRACT.DESCRIPTION,
    icon: FAIRBOT_QUICK_ACTIONS.ICONS.DOCUMENT,
    color: FAIRBOT_QUICK_ACTIONS.COLORS.ORANGE,
    requiresFile: false,
    initialMessage: FAIRBOT_QUICK_ACTIONS_TEXT.GENERATE_CONTRACT.INITIAL_MESSAGE,
    requiredPermission: FAIRBOT_QUICK_ACTIONS.PERMISSIONS.MANAGE_DOCUMENTS,
  },
]

export const quickActionLabels = {
  gridLabel: FAIRBOT_LABELS.PROMPT_QUESTION,
} as const
