import { useCallback, useState } from 'react'

// TODO: [Backend Integration] This hook is ready for async export operations.
// Currently unused as CSV export is synchronous (generated in browser).
// Use this hook when:
// 1. Export is generated by backend (e.g., GET /api/compliance/export/:id)
// 2. Need to show loading spinner during export
// 3. Need to handle export errors with user feedback

type ExportHandler = () => Promise<void> | void

export function useExportHandler(onExport?: ExportHandler) {
  const [isExporting, setIsExporting] = useState(false)
  const [error, setError] = useState<Error | null>(null)

  const handleExport = useCallback(async () => {
    if (!onExport || isExporting) return
    setIsExporting(true)
    setError(null)
    try {
      await onExport()
    } catch (err) {
      setError(err as Error)
    } finally {
      setIsExporting(false)
    }
  }, [onExport, isExporting])

  return { isExporting, error, handleExport }
}
