// <auto-generated />
using System;
using FairWorkly.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FairWorkly.Infrastructure.Migrations
{
    [DbContext(typeof(FairWorklyDbContext))]
    [Migration("20260131000438_MakeEmployeeEmailOptional")]
    partial class MakeEmployeeEmailOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FairWorkly.Domain.Auth.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ABN")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("abn");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CurrentEmployeeCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_employee_count");

                    b.Property<string>("IndustryType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSubscriptionActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_subscription_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("postcode");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_end_date");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_start_date");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_tier");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suburb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("ABN")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_abn");

                    b.HasIndex("ContactEmail")
                        .HasDatabaseName("ix_organizations_contact_email");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_organizations_created_by_user_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_organizations_updated_by_user_id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Auth.Entities.OrganizationAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("AwardType")
                        .HasColumnType("integer")
                        .HasColumnName("award_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer")
                        .HasColumnName("employee_count");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_awards");

                    b.HasIndex("OrganizationId", "AwardType")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_awards_organization_id_award_type");

                    b.HasIndex("OrganizationId", "IsPrimary")
                        .HasDatabaseName("ix_organization_awards_organization_id_is_primary");

                    b.ToTable("organization_awards", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_users_created_by_user_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_users_employee_id");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_id")
                        .HasFilter("google_id IS NOT NULL");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_users_updated_by_user_id");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_organization_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Awards.Entities.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AwardCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("award_code");

                    b.Property<int>("AwardType")
                        .HasColumnType("integer")
                        .HasColumnName("award_type");

                    b.Property<decimal>("CasualLoadingRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("casual_loading_rate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_consecutive_days");

                    b.Property<int>("MealBreakMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("meal_break_minutes");

                    b.Property<int>("MealBreakThresholdHours")
                        .HasColumnType("integer")
                        .HasColumnName("meal_break_threshold_hours");

                    b.Property<int>("MinimumRestPeriodHours")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_rest_period_hours");

                    b.Property<decimal>("MinimumShiftHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("minimum_shift_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrdinaryWeeklyHours")
                        .HasColumnType("integer")
                        .HasColumnName("ordinary_weekly_hours");

                    b.Property<decimal>("PublicHolidayPenaltyRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("public_holiday_penalty_rate");

                    b.Property<decimal>("SaturdayPenaltyRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("saturday_penalty_rate");

                    b.Property<decimal>("SundayPenaltyRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("sunday_penalty_rate");

                    b.HasKey("Id")
                        .HasName("pk_awards");

                    b.HasIndex("AwardCode")
                        .IsUnique()
                        .HasDatabaseName("ix_awards_award_code");

                    b.HasIndex("AwardType")
                        .IsUnique()
                        .HasDatabaseName("ix_awards_award_type");

                    b.ToTable("awards", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Awards.Entities.AwardLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AwardId")
                        .HasColumnType("uuid")
                        .HasColumnName("award_id");

                    b.Property<decimal>("CasualHourlyRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("casual_hourly_rate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("FullTimeHourlyRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("full_time_hourly_rate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("level_name");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer")
                        .HasColumnName("level_number");

                    b.Property<decimal>("PartTimeHourlyRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("part_time_hourly_rate");

                    b.HasKey("Id")
                        .HasName("pk_award_levels");

                    b.HasIndex("AwardId", "LevelNumber", "EffectiveFrom")
                        .HasDatabaseName("ix_award_levels_award_id_level_number_effective_from");

                    b.HasIndex("AwardId", "LevelNumber", "IsActive")
                        .HasDatabaseName("ix_award_levels_award_id_level_number_is_active");

                    b.ToTable("award_levels", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Documents.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ComplianceDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("compliance_deadline");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLegallyRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legally_required");

                    b.Property<bool>("IsProvided")
                        .HasColumnType("boolean")
                        .HasColumnName("is_provided");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ProvidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provided_at");

                    b.Property<string>("ProvidedMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provided_method");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UploadedFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uploaded_file_name");

                    b.Property<string>("UploadedFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("uploaded_file_path");

                    b.Property<long?>("UploadedFileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_file_size");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_documents_created_by_user_id");

                    b.HasIndex("IsProvided")
                        .HasDatabaseName("ix_documents_is_provided");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_documents_updated_by_user_id");

                    b.HasIndex("EmployeeId", "DocumentType")
                        .HasDatabaseName("ix_documents_employee_id_document_type");

                    b.HasIndex("OrganizationId", "DocumentType")
                        .HasDatabaseName("ix_documents_organization_id_document_type");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Employees.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<int>("AwardLevelNumber")
                        .HasColumnType("integer")
                        .HasColumnName("award_level_number");

                    b.Property<int>("AwardType")
                        .HasColumnType("integer")
                        .HasColumnName("award_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_number");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer")
                        .HasColumnName("employment_type");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int?>("GuaranteedHours")
                        .HasColumnType("integer")
                        .HasColumnName("guaranteed_hours");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("SuperannuationFund")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("superannuation_fund");

                    b.Property<string>("SuperannuationMemberNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("superannuation_member_number");

                    b.Property<string>("TaxFileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_file_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_employees_created_by_user_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_employees_updated_by_user_id");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_organization_id_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("OrganizationId", "EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_organization_id_employee_number")
                        .HasFilter("employee_number IS NOT NULL");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Payroll.Entities.PayrollIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_value");

                    b.Property<decimal?>("AffectedUnits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("affected_units");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_type");

                    b.Property<string>("ContextLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("context_label");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailedExplanation")
                        .HasColumnType("text")
                        .HasColumnName("detailed_explanation");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<decimal?>("ExpectedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("expected_value");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PayrollValidationId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_validation_id");

                    b.Property<Guid>("PayslipId")
                        .HasColumnType("uuid")
                        .HasColumnName("payslip_id");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("UnitType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_type");

                    b.Property<string>("WarningMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("warning_message");

                    b.HasKey("Id")
                        .HasName("pk_payroll_issues");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_payroll_issues_employee_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_payroll_issues_organization_id");

                    b.HasIndex("PayrollValidationId")
                        .HasDatabaseName("ix_payroll_issues_payroll_validation_id");

                    b.HasIndex("PayslipId")
                        .HasDatabaseName("ix_payroll_issues_payslip_id");

                    b.HasIndex("ResolvedByUserId")
                        .HasDatabaseName("ix_payroll_issues_resolved_by_user_id");

                    b.ToTable("payroll_issues", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Payroll.Entities.PayrollValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BaseRateCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("base_rate_check_performed");

                    b.Property<bool>("CasualLoadingCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("casual_loading_check_performed");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CriticalIssuesCount")
                        .HasColumnType("integer")
                        .HasColumnName("critical_issues_count");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("PassedCount")
                        .HasColumnType("integer")
                        .HasColumnName("passed_count");

                    b.Property<DateTimeOffset>("PayPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pay_period_end");

                    b.Property<DateTimeOffset>("PayPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pay_period_start");

                    b.Property<bool>("PenaltyRateCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("penalty_rate_check_performed");

                    b.Property<bool>("STPCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("stp_check_performed");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("SuperannuationCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("superannuation_check_performed");

                    b.Property<int>("TotalIssuesCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_issues_count");

                    b.Property<int>("TotalPayslips")
                        .HasColumnType("integer")
                        .HasColumnName("total_payslips");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_payroll_validations");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_payroll_validations_created_by_user_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_payroll_validations_organization_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_payroll_validations_updated_by_user_id");

                    b.ToTable("payroll_validations", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Payroll.Entities.Payslip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Allowances")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("allowances");

                    b.Property<int>("AwardType")
                        .HasColumnType("integer")
                        .HasColumnName("award_type");

                    b.Property<decimal?>("CasualLoadingPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("casual_loading_pay");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employee_name");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_number");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer")
                        .HasColumnName("employment_type");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_reference");

                    b.Property<decimal>("GrossPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_pay");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("NetPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_pay");

                    b.Property<decimal>("OrdinaryHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ordinary_hours");

                    b.Property<decimal>("OrdinaryPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ordinary_pay");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal?>("OtherDeductions")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("other_deductions");

                    b.Property<decimal?>("OvertimeHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("overtime_hours");

                    b.Property<decimal?>("OvertimePay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("overtime_pay");

                    b.Property<DateTimeOffset>("PayDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pay_date");

                    b.Property<DateTimeOffset>("PayPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pay_period_end");

                    b.Property<DateTimeOffset>("PayPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pay_period_start");

                    b.Property<Guid?>("PayrollValidationId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_validation_id");

                    b.Property<decimal>("PublicHolidayHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("public_holiday_hours");

                    b.Property<decimal>("PublicHolidayPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("public_holiday_pay");

                    b.Property<decimal>("SaturdayHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saturday_hours");

                    b.Property<decimal>("SaturdayPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saturday_pay");

                    b.Property<string>("SourceData")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_data");

                    b.Property<decimal>("SundayHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sunday_hours");

                    b.Property<decimal>("SundayPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sunday_pay");

                    b.Property<decimal>("Superannuation")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("superannuation");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_payslips");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_payslips_created_by_user_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_payslips_employee_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_payslips_organization_id");

                    b.HasIndex("PayrollValidationId")
                        .HasDatabaseName("ix_payslips_payroll_validation_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_payslips_updated_by_user_id");

                    b.ToTable("payslips", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.Roster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finalized");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("TotalEmployees")
                        .HasColumnType("integer")
                        .HasColumnName("total_employees");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_hours");

                    b.Property<int>("TotalShifts")
                        .HasColumnType("integer")
                        .HasColumnName("total_shifts");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("week_end_date");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("week_start_date");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_rosters");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_rosters_created_by_user_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_rosters_updated_by_user_id");

                    b.HasIndex("OrganizationId", "WeekStartDate")
                        .HasDatabaseName("ix_rosters_organization_id_week_start_date");

                    b.HasIndex("OrganizationId", "Year", "WeekNumber")
                        .HasDatabaseName("ix_rosters_organization_id_year_week_number");

                    b.ToTable("rosters", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.RosterIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("actual_value");

                    b.Property<string>("AffectedDates")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("affected_dates");

                    b.Property<int?>("AffectedShiftsCount")
                        .HasColumnType("integer")
                        .HasColumnName("affected_shifts_count");

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("check_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DetailedExplanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detailed_explanation");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<decimal?>("ExpectedValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("expected_value");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<bool>("IsWaived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_waived");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recommendation");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<Guid>("RosterValidationId")
                        .HasColumnType("uuid")
                        .HasColumnName("roster_validation_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<DateTimeOffset?>("WaivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waived_at");

                    b.Property<Guid?>("WaivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("waived_by_user_id");

                    b.Property<string>("WaiverReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("waiver_reason");

                    b.HasKey("Id")
                        .HasName("pk_roster_issues");

                    b.HasIndex("CheckType")
                        .HasDatabaseName("ix_roster_issues_check_type");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_roster_issues_employee_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_roster_issues_organization_id");

                    b.HasIndex("ResolvedByUserId")
                        .HasDatabaseName("ix_roster_issues_resolved_by_user_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_roster_issues_shift_id");

                    b.HasIndex("WaivedByUserId")
                        .HasDatabaseName("ix_roster_issues_waived_by_user_id");

                    b.HasIndex("RosterValidationId", "EmployeeId")
                        .HasDatabaseName("ix_roster_issues_roster_validation_id_employee_id");

                    b.HasIndex("RosterValidationId", "Severity")
                        .HasDatabaseName("ix_roster_issues_roster_validation_id_severity");

                    b.ToTable("roster_issues", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.RosterValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AffectedEmployees")
                        .HasColumnType("integer")
                        .HasColumnName("affected_employees");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CriticalIssuesCount")
                        .HasColumnType("integer")
                        .HasColumnName("critical_issues_count");

                    b.Property<int>("FailedShifts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_shifts");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("MaxConsecutiveDaysCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("max_consecutive_days_check_performed");

                    b.Property<bool>("MealBreakCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("meal_break_check_performed");

                    b.Property<bool>("MinimumShiftHoursCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("minimum_shift_hours_check_performed");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("PassedShifts")
                        .HasColumnType("integer")
                        .HasColumnName("passed_shifts");

                    b.Property<bool>("RestPeriodCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("rest_period_check_performed");

                    b.Property<Guid>("RosterId")
                        .HasColumnType("uuid")
                        .HasColumnName("roster_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalIssuesCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_issues_count");

                    b.Property<int>("TotalShifts")
                        .HasColumnType("integer")
                        .HasColumnName("total_shifts");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("week_end_date");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("week_start_date");

                    b.Property<bool>("WeeklyHoursCheckPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("weekly_hours_check_performed");

                    b.HasKey("Id")
                        .HasName("pk_roster_validations");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_roster_validations_created_by_user_id");

                    b.HasIndex("RosterId")
                        .IsUnique()
                        .HasDatabaseName("ix_roster_validations_roster_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_roster_validations_updated_by_user_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_roster_validations_organization_id_status");

                    b.ToTable("roster_validations", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<bool>("HasMealBreak")
                        .HasColumnType("boolean")
                        .HasColumnName("has_meal_break");

                    b.Property<bool>("HasRestBreaks")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rest_breaks");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOnCall")
                        .HasColumnType("boolean")
                        .HasColumnName("is_on_call");

                    b.Property<bool>("IsPublicHoliday")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public_holiday");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<int?>("MealBreakDuration")
                        .HasColumnType("integer")
                        .HasColumnName("meal_break_duration");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublicHolidayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("public_holiday_name");

                    b.Property<int?>("RestBreaksDuration")
                        .HasColumnType("integer")
                        .HasColumnName("rest_breaks_duration");

                    b.Property<Guid>("RosterId")
                        .HasColumnType("uuid")
                        .HasColumnName("roster_id");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_shifts");

                    b.HasIndex("EmployeeId", "Date")
                        .HasDatabaseName("ix_shifts_employee_id_date");

                    b.HasIndex("OrganizationId", "Date")
                        .HasDatabaseName("ix_shifts_organization_id_date");

                    b.HasIndex("RosterId", "EmployeeId", "Date")
                        .HasDatabaseName("ix_shifts_roster_id_employee_id_date");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("FairWorkly.Domain.Auth.Entities.Organization", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organizations_users_created_by_user_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organizations_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Auth.Entities.OrganizationAward", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany("OrganizationAwards")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_awards_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("FairWorkly.Domain.Auth.Entities.User", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_created_by_user_id");

                    b.HasOne("FairWorkly.Domain.Employees.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_employees_employee_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Awards.Entities.AwardLevel", b =>
                {
                    b.HasOne("FairWorkly.Domain.Awards.Entities.Award", "Award")
                        .WithMany("Levels")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_award_levels_awards_award_id");

                    b.Navigation("Award");
                });

            modelBuilder.Entity("FairWorkly.Domain.Documents.Entities.Document", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documents_users_created_by_user_id");

                    b.HasOne("FairWorkly.Domain.Employees.Entities.Employee", "Employee")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documents_employees_employee_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documents_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Employees.Entities.Employee", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employees_users_created_by_user_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employees_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Payroll.Entities.PayrollIssue", b =>
                {
                    b.HasOne("FairWorkly.Domain.Employees.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_issues_employees_employee_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_issues_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Payroll.Entities.PayrollValidation", "PayrollValidation")
                        .WithMany("Issues")
                        .HasForeignKey("PayrollValidationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_issues_payroll_validations_payroll_validation_id");

                    b.HasOne("FairWorkly.Domain.Payroll.Entities.Payslip", "Payslip")
                        .WithMany("Issues")
                        .HasForeignKey("PayslipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_issues_payslips_payslip_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payroll_issues_users_resolved_by_user_id");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("PayrollValidation");

                    b.Navigation("Payslip");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Payroll.Entities.PayrollValidation", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("fk_payroll_validations_users_created_by_user_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_validations_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("fk_payroll_validations_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Payroll.Entities.Payslip", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("fk_payslips_users_created_by_user_id");

                    b.HasOne("FairWorkly.Domain.Employees.Entities.Employee", "Employee")
                        .WithMany("Payslips")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payslips_employees_employee_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payslips_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Payroll.Entities.PayrollValidation", "PayrollValidation")
                        .WithMany("Payslips")
                        .HasForeignKey("PayrollValidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_payslips_payroll_validations_payroll_validation_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("fk_payslips_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("PayrollValidation");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.Roster", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rosters_users_created_by_user_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rosters_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rosters_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.RosterIssue", b =>
                {
                    b.HasOne("FairWorkly.Domain.Employees.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_issues_employees_employee_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_issues_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_issues_users_resolved_by_user_id");

                    b.HasOne("FairWorkly.Domain.Roster.Entities.RosterValidation", "RosterValidation")
                        .WithMany("Issues")
                        .HasForeignKey("RosterValidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roster_issues_roster_validations_roster_validation_id");

                    b.HasOne("FairWorkly.Domain.Roster.Entities.Shift", "Shift")
                        .WithMany("Issues")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_roster_issues_shifts_shift_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "WaivedByUser")
                        .WithMany()
                        .HasForeignKey("WaivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_issues_users_waived_by_user_id");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("RosterValidation");

                    b.Navigation("Shift");

                    b.Navigation("WaivedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.RosterValidation", b =>
                {
                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_validations_users_created_by_user_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_validations_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Roster.Entities.Roster", "Roster")
                        .WithOne("RosterValidation")
                        .HasForeignKey("FairWorkly.Domain.Roster.Entities.RosterValidation", "RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roster_validations_rosters_roster_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_validations_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");

                    b.Navigation("Roster");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.Shift", b =>
                {
                    b.HasOne("FairWorkly.Domain.Employees.Entities.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_employees_employee_id");

                    b.HasOne("FairWorkly.Domain.Auth.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_organizations_organization_id");

                    b.HasOne("FairWorkly.Domain.Roster.Entities.Roster", "Roster")
                        .WithMany("Shifts")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_rosters_roster_id");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("FairWorkly.Domain.Auth.Entities.Organization", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("OrganizationAwards");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FairWorkly.Domain.Awards.Entities.Award", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("FairWorkly.Domain.Employees.Entities.Employee", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Payslips");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("FairWorkly.Domain.Payroll.Entities.PayrollValidation", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Payslips");
                });

            modelBuilder.Entity("FairWorkly.Domain.Payroll.Entities.Payslip", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.Roster", b =>
                {
                    b.Navigation("RosterValidation");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.RosterValidation", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("FairWorkly.Domain.Roster.Entities.Shift", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
